# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-23 20:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='richcontent',
            name='title',
            field=models.CharField(help_text='Enter a title for this content, this is for internal use and not displayed to users.', max_length=150),
        ),
    ]
