# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-23 22:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0002_auto_20210923_2336'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(help_text='Main document header, this should be the H1 tag unless mentioned otherwise.', max_length=250)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='richcontent',
            name='title',
            field=models.CharField(help_text='Enter an internal title for this content, this is for internal use and not displayed to users.', max_length=150),
        ),
        migrations.AddField(
            model_name='document',
            name='content',
            field=models.ForeignKey(help_text='The main content of this document', on_delete=django.db.models.deletion.CASCADE, to='content_manager.RichContent'),
        ),
    ]
