# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-09-27 14:17
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_manager', '0003_auto_20210924_0134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='content',
            field=ckeditor.fields.RichTextField(help_text='Keep empty to display default (if default exists)'),
        ),
        migrations.DeleteModel(
            name='RichContent',
        ),
    ]
